# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SG_PSI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SG_PSI
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Quick'
  pod 'Nimble'

  target 'SG_PSITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SG_PSIUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
